spring.application.name=enrollment-system

# 1. Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# 3. Forzar a Hibernate a RECREAR las tablas desde cero cada vez que inicia la app
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Forzar a Spring a esperar que Hibernate cree las tablas ANTES de ejecutar data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# 5. Puerto
server.port=8088